openapi: 3.0.0
info:
  title: House Management API
  version: 1.0.0
  description: API for managing house listings and their details.
servers:
  - url: http://localhost:3000/api
security:
  - bearerAuth: []  # Define global security scheme

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    House:
      type: object
      properties:
        ownerID:
          type: number
        ownerName:
          type: string
        postedBy:
          type: string
          enum: [admin, owner, subAdmin]
          default: admin
        houseType:
          type: string
        weekendPrice:
          type: number
        rentType:
          type: string
        status:
          type: string
          enum: [available, rented, blocked]
          default: available
        adminConfirmation:
          type: string
          enum: [pending, confirmed, cancelled]
          default: pending
        description:
          type: string
        pricePerDay:
          type: number
        address:
          type: string
        country:
          type: string
        street:
          type: string
        ville:
          type: string
        state:
          type: string
        floor:
          type: string
        zipCode:
          type: number
        latitude:
          type: number
        longitude:
          type: number
        created_at:
          type: string
          format: date-time
          default: '2023-12-27T00:00:00Z'  # Default format for date-time
        note:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        guests:
          type: number
        bedrooms:
          type: number
        beds:
          type: number
        bathrooms:
          type: number
        houseEquipments:
          type: array
          items:
            type: string
          maxItems: 20  # Maximum number of house equipments
        houseName:
          type: string
        category:
          type: array
          items:
            type: string
          maxItems: 20 
        reservationType:
          type: string
        priceOverWeek:
          type: number
        priceOverMonth:
          type: number
        cleaningPriceShort:
          type: number
        cleaningPriceLong:
          type: number

paths:
  /api/methods/houses:
    post:
      summary: Create a new house listing
      security:
        - bearerAuth: []  # Specific security for this endpoint
      requestBody:
        required: false
        content:
          multipart/form-data:  # Use multipart for file uploads
            schema:
              type: object
              properties:
                ownerID:
                  type: number
                ownerName:
                  type: string
                postedBy:
                  type: string
                  enum: [admin, owner, subAdmin]
                  default: admin
                images:
                  type: array
                  items:
                    type: string
                    format: binary  # Indicates file upload
                  maxItems: 20
                houseType:
                  type: string
                description:
                  type: string
                pricePerDay:
                  type: number
                address:
                  type: string
                category:
                  type: array
                  items:
                    type: string
                  maxItems: 20
      responses:
        '201':
          description: House created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/House'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
