openapi: 3.0.0
info:
  title: User Password Management API
  version: 1.0.0
  description: API for requesting password resets and updating passwords for users.

servers:
  - url: http://localhost:3000/api

security:
  - bearerAuth: []  # Applies Bearer token security globally

paths:
  /api/password/reset:
    post:
      summary: Request password reset
      operationId: requestPasswordReset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: The email address of the user requesting a password reset.
                  example: user@example.com
              required:
                - email
      responses:
        '200':
          description: Password reset email sent successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Password reset email sent.
        '400':
          description: Validation failed or user not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Failed to update password reset token.

  /api/password/update:
    post:
      summary: Update user password
      operationId: updatePassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: The password reset token sent to the user's email.
                  example: eyJhbGciOiJIUzI1NiIsInR...
                newPassword:
                  type: string
                  description: The new password for the user.
                  example: NewPassword123!
              required:
                - token
                - newPassword
      responses:
        '200':
          description: Password updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Password updated successfully.
        '400':
          description: Validation failed or token is required.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Token and new password are required.
        '401':
          description: Unauthorized due to invalid token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid password reset token.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Failed to update password.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
